export const ADD_USER_FROM_LOGIN = 'ADD_USER_FROM_LOGIN';
export const ADD_EMAIL_FROM_LOGIN = 'ADD_EMAIL_FROM_LOGIN';
export const ADD_PASSWORD_FROM_LOGIN = 'ADD_PASSWORD_FROM_LOGIN';
export const ADD_TOKEN_TO_STATE = 'ADD_TOKEN_TO_STATE';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';

export const ADD_COURSES_FROM_FETCH = 'ADD_COURSES_FROM_FETCH';