export const ADD_USER_FROM_LOGIN = 'ADD_USER_FROM_LOGIN';
export const ADD_EMAIL_FROM_LOGIN = 'ADD_EMAIL_FROM_LOGIN';
export const ADD_PASSWORD_FROM_LOGIN = 'ADD_PASSWORD_FROM_LOGIN';
export const ADD_TOKEN_TO_STATE = 'ADD_TOKEN_TO_STATE';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const ADD_NAME_FROM_REG = 'ADD_NAME_FROM_REG';
export const ADD_EMAIL_FROM_REG = 'ADD_EMAIL_FROM_REG';
export const ADD_PASS_FROM_REG = 'ADD_PASS_FROM_REG';
export const SET_VALUE_FROM_LOGIN = 'SET_VALUE_FROM_LOGIN';
export const SET_VALUE = 'SET_VALUE';
export const SET_EMAIL = 'SET_EMAIL';

export const ADD_COURSES_FROM_FETCH = 'ADD_COURSES_FROM_FETCH';

